import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '@/styles/Home.module.scss'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>
          To do List
        </title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        
          <h1>Oi Prof Murilo, esse é o seu To Do List </h1>
          <p>mas primeiro... faça seu login</p>
          
          <form>
            <label htmlFor="login">Login</label>
            <input type="login" id="login"  />
            <label htmlFor="senha">Senha</label>
            <input type="senha" id="senha" />
          </form>
    <button>Entrar</button>
       
      </main>
    </>
  )
}
